### ISSUE TITLE
Increasing memory consumption

### ISSUE THREAD

**Issue by yehonatanz** [tomlegkov/marine-core#18]
When feeding marine with lots of packets (hundreds of thousands and more), memory consumption is steadily increasing.
This should be addressed.
Why does it happen? Is it us? Is it wireshark? Can we solve it without modifying wireshark sources too drastically?

**Comment by royreznik** [comment]
Can you provide a script that makes this happend?

**Comment by yehonatanz** [comment]
Unlinked the PR since it doesn't resolve this issue completely.

**Comment by yehonatanz** [comment]
#22 did solve this issue eventually.
Closing.
