### ISSUE TITLE
Disable Parsing Options

### ISSUE THREAD

**Issue by tomlegkov** [tomlegkov/marine-core#19]
Since Marine is a per-packet parser (and doesn't support conversations and fragmentation), we can disable some options to speed up parsing and save some memory. This is a list of TCP options (available through Edit ->Preferences -> Protocols):
![image](https://user-images.githubusercontent.com/9741091/78251986-d147a180-74fa-11ea-8cef-c2a45ce183f1.png)

Need to check how tshark supports disabling options and apply the logic here. We should be able to disable as many options as possible (without affecting the parsing results).

Some options which can definitely be disabled:
- Analyze TCP sequence numbers
- Relative sequence numbers
- Track number of bytes in flight
- Reassemble out-of-order segments
- Validate the TCP checksum if possible

There are also options for IPv4, IPv6, etc. Need to scan them all and disable as many as possible.

**Comment by yehonatanz** [comment]
After much work, @royreznik determined this to be non effective
